name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics/github-metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: Chen-Kaixiang-HuiAn
          template: classic
          base: header, activity, repositories
          config_timezone: Asia/Shanghai
          config_twemoji: yes
          config_display: large

          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming, data, prose
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage, lines
          plugin_languages_limit: 0
          plugin_languages_sections: most-used
          plugin_languages_other: yes
          repositories_affiliations: owner, collaborator, organization_member

          plugin_calendar: yes
          plugin_calendar_limit: 0
